version: '3'

services:
  todo-db:
    container_name: todo-db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 'postgres'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always

volumes:
  todo-db-data:
